### PR TITLE
Change bblfsh/web port

### PR DESCRIPTION
**Pull request by smacker**
Change default value because we change it in bblfsh/web: https://github.com/bblfsh/web/issues/148

### CODE REVIEW

**Comment by rporres** [comment]
LGTM. Can you please change the Chart version?

**Comment by smacker** [comment]
Updated. Please keep in mind we didn't release the image with this change yet. It waits for the last touches on uast2.

We are going to create an issue for new deployment and update bblfsh/drivers there when the image is ready.

**Comment by smacker** [comment]
My bad. `targetPort` should be changed not `port`. Fixed.

**Comment by rporres** [comment]
This will be taken care in (the broader in scope) https://github.com/src-d/charts/pull/106

**Pull request closed without merging**
