### PR TITLE
Add http health probes to lookout

### PR DESCRIPTION
**Pull request by carlosms**
Part of https://github.com/src-d/lookout/issues/180.
Depends on https://github.com/src-d/lookout/pull/252.

### CODE REVIEW

**Comment by rporres** [comment]
Looks good, but I have concerns with naming and default values. See https://github.com/src-d/lookout/pull/252#pullrequestreview-155149373

**Comment by carlosms** [comment]
Changes to make the env vars more descriptive done in 5ea33d1.

**Comment by rporres** [comment]
looks good. Please squash your changes and I will merge it when src-d/lookout#252 is merged

**Comment by carlosms** [comment]
Done, and done!

**Pull request merged**
